---
extends: default
rules:
    braces:
        max-spaces-inside: 1
    new-lines:
        level: warning
        type: unix
    line-length:
        max: 500
    comments:
        min-spaces-from-content: 1
    truthy:
        allowed-values: ["true", "false", "on"]
