---
name: MegaLinter

on:
    push:
    pull_request:
        branches: [master, main]

env:
    APPLY_FIXES: all
    APPLY_FIXES_EVENT: pull_request
    APPLY_FIXES_MODE: commit

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: MegaLinter
              id: ml
              uses: oxsecurity/megalinter@v8
              env:
                  VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # DISABLE: COPYPASTE,SPELL

            - name: Archive production artifacts
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                  name: MegaLinter reports
                  path: |
                      megalinter-reports
                      mega-linter.log

            - name: Create Pull Request with applied fixes
              id: cpr
              if: >-
                  steps.ml.outputs.has_updated_sources == 1 &&
                  (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) &&
                  env.APPLY_FIXES_MODE == 'pull_request' &&
                  (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) &&
                  !contains(github.event.head_commit.message, 'skip fix')
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
                  commit-message: "[MegaLinter] Apply linters automatic fixes"
                  title: "[MegaLinter] Apply linters automatic fixes"
                  labels: bot
            - name: Create PR output
              if: >-
                  steps.ml.outputs.has_updated_sources == 1 &&
                  (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) &&
                  env.APPLY_FIXES_MODE == 'pull_request' &&
                  (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) &&
                  !contains(github.event.head_commit.message, 'skip fix')
              run: |
                  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

            - name: Prepare commit
              if: >-
                  steps.ml.outputs.has_updated_sources == 1 &&
                  (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) &&
                  env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' &&
                  (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) &&
                  !contains(github.event.head_commit.message, 'skip fix')
              run: sudo chown -Rc $UID .git/
            - name: Commit and push applied linter fixes
              if: >-
                  steps.ml.outputs.has_updated_sources == 1 &&
                  (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) &&
                  env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' &&
                  (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) &&
                  !contains(github.event.head_commit.message, 'skip fix')
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
                  commit_message: "[MegaLinter] Apply linters fixes"
                  commit_user_name: megalinter-bot
                  commit_user_email: 129584137+megalinter-bot@users.noreply.github.com
