name: Testing Action

on: [push, pull_request]

jobs:
  test_go:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18.x

    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Test
    #  run: go test ./...

    - name: build
      run: go build -o main

  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --pull -t test .

      - name: Test Docker image
        run: docker image inspect test

  test_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Testing action
        uses: ./
        with:
          playbook: tests/playbook.yml
          inventory: tests/hosts.yml
          galaxy_file: tests/requirements.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
